### ISSUE TITLE
Question about PyPI

### ISSUE THREAD

**Issue by sijokun** [CWKevo/pyEditorJS#1]
Are you still planning to publish this library? 
I'm potentially interested in using it for my site, if you're not going then I'll have to fork it :(

**Comment by SKevo18** [comment]
Yes, eventually, I might look at it this week if I have time.

Forks and/or PRs are welcome, though :)

**Comment by sijokun** [comment]
> Yes, eventually, I might look at it this week if I have time.
> 
> Forks and/or PRs are welcome, though :)

If we will use this library, then I will definitely try to make pull requests. Now we choose between CKEditor and Editor.js :)


Thanks for the quick response!

**Comment by SKevo18** [comment]
FYI initial version (full recode) is now available at https://pypi.org/project/pyeditorjs/

HTML sanitization and rendering works. All blocks from the example at [Editor.js's main page](https://editorjs.io) should be compatible. Please, let me know if you have any suggestions or improvements!

[pyeditorjs-1.0.0b0.tar.gz](https://github.com/CWKevo/pyEditorJS/files/9482921/pyeditorjs-1.0.0b0.tar.gz)

**Comment by sijokun** [comment]
> FYI initial version (full recode) is now available at https://pypi.org/project/pyeditorjs/
> 
> HTML sanitization and rendering works. All blocks from the example at [Editor.js's main page](https://editorjs.io) should be compatible. Please, let me know if you have any suggestions or improvements!
> 
> [pyeditorjs-1.0.0b0.tar.gz](https://github.com/CWKevo/pyEditorJS/files/9482921/pyeditorjs-1.0.0b0.tar.gz)

First of all, thank you! I'm currently working on a fork of editorjs/image for improved work with video, I think I'll have to make some fixes for it, but I think I can add them myself and send a pull request :)

BTW, if you ever need to contact me in the future, you can use telegram t.me/luck20yan or email a@slnk.icu, I try to monitor github, but not always :)

**Comment by sijokun** [comment]
```<div class="cdx-block image-tool image-tool--filled   "><div class="image-tool__image"><div class="image-tool__image-preloader"></div><img class="image-tool__image-picture" src="/uploads/5b3cab96-8149-4d15-9a04-368149e9f503.jpeg"/></div><div class="image-tool__caption" data-placeholder="123 123 123&lt;br&gt;"></div></div></div>```


As expected for the image with errors, but it's not terrible, since I planned to rewrite this part of your project anyway :)

**Comment by SKevo18** [comment]
Yes, bugs and security issues are expected as I didn't test it much and did most of it in a hurry.

Do you have Discord? It works better for me, but I don't mind using Telegram either

**Comment by sijokun** [comment]
> Yes, bugs and security issues are expected as I didn't test it much and did most of it in a hurry.
> 
> Do you have Discord? It works better for me, but I don't mind using Telegram either

telegram is better, I open discord even less often than github :)
